var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var comentarioSchema = new Schema({
    texto: { type: String, required: true },
    entrada: { type: Schema.Types.ObjectId, ref: 'Entrada', required: true },
    autor: { type: Schema.Types.ObjectId, ref: 'Usuario', required: true },
    comentario: { type: Schema.Types.ObjectId, ref: 'Comentario' }
});

module.exports = mongoose.model('Comenta                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rio', comentarioSchema);